import Head from 'next/head';
import { Banner } from '../components/Banner';
import { MeduimCard } from '../components/MediumCard';
import { Header } from '../components/Header';
import { SmallCard } from '../components/SmallCard';
import { LargeCard } from '../components/LargeCard';
import { Footer } from '../components/Footer';
export default function Home({ exploreData, cardsData }) {
  return (
    <div className=''>
      <Head>
        <title>Memo's Books</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Banner />
      <main className='max-w-7xl mx-auto px-8 sm:px-16'>
        <section className='pt-6 '>
          <h2 className='text-4xl font-semibold pb-5'>My favorite Books</h2>
          {/* pull some data from server - API endpoints*/}
          <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4'>
            {exploreData?.map((item) => {
              return (
                <SmallCard
                  key={item.id}
                  img={item.img}
                  title={item.title}
                  rank={item.rank}
                  idCode={item.idcode}
                />
              );
            })}
          </div>
        </section>
        <sectin>
          <h2 className='text-4xl font-semibold py-8'>Live Anywere</h2>
          <div className='flex space-x-3 overflow-scroll scrollbar-hide'>
            {cardsData?.map((item, i) => {
              return <MeduimCard key={i} img={item.img} title={item.title} />;
            })}
          </div>
        </sectin>
        <LargeCard
          img='/images/linux-03.png'
          title='The Greatest Operating System '
          description='Wishes curated by ...'
          buttonText='Get insired'
        />
      </main>
      <Footer />
    </div>
  );
}

export async function getStaticProps() {
  const exploreData = await fetch(
    'https://edwardtanguay.netlify.app/share/books.json'
  ).then((result) => result.json());

  const cardsData = await fetch('http://links.papareact.com/zp1').then(
    (result) => result.json()
  );

  return {
    props: {
      exploreData: exploreData,
      cardsData: cardsData,
    },
  };
}
