import Head from 'next/head';
import { Banner } from '../components/Banner';

import { Header } from '../components/Header';

export default function Home({ exploreData }) {
  return (
    <div className=''>
      <Head>
        <title>Memo Airbnb</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Banner />
      <main className='max-w-7xl mx-auto px-8 sm:px-16'>
        <section className='pt-6 '>
          <h2 className='text-4xl font-semibold pb-5'>Explore Nearby</h2>
          {/* pull some data from server - API endpoints*/}
          {exploreData?.map((item) => {
            return <h1 className='text-xl'>{item.location}</h1>;
          })}
        </section>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const exploreData = await fetch('http://links.papareact.com/pyp').then(
    (result) => result.json()
  );

  return {
    props: {
      exploreData: exploreData,
    },
  };
}
