import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className='bg-indigo-900 text-white flex flex-col items-center justify-center min-h-screen py-2'>
      <Head>
        <title>Memo Airbnb</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>Lets build Airbnb</h1>
    </div>
  );
}
